In [11]:
#câu 1
import numpy as np
A = np.array([3, -2, 1, 4])
B = np.array([-1, 5, 0, 2])
C = np.array([[2, -1, 3],[1, 4, -2],[0, 2, 5]])
tong = A + B
tich_so = 2*A + 3*B
print("A + B =", tong)
print("2A + 3B =", tich_so)
tich_vo_huong = np.dot(A, B)
cos_theta = tich_vo_huong / (np.linalg.norm(A) * np.linalg.norm(B))
goc = np.degrees(np.arccos(cos_theta))
print("Tích vô hướng=", tich_vo_huong)
print("Góc  =", round(goc, 3))
ketqua = np.dot(C, C.T)
print("C x C^T =", ketqua)

# câu 2
M = np.array([[2, -1, 3, 0],[1, 4, -2, 5],[0, 2, 6, -3],[-1, 0, 1, 4]])
N = np.array([[1, 3, -2, 0],[4, -1, 5, 2],[0, 2, 3, -1],[-3, 1, 0, 4]])
MN = M @ N
print("M x N =", MN)
from numpy.linalg import det
dinh_thuc_M = det(M)
print("Định thức =", dinh_thuc_M)
hang_N = np.linalg.matrix_rank(N)
print("Hạng của N =", hang_N)

# câu 3
P = np.array([[3, -1, 0, 2],[1, 4, -2, 0],[0, 1, 5, -1],[2, 0, 1, 3]])
b = np.array([6, 8, 3, 7])
try:
    P_inv = np.linalg.inv(P)
    print("Ma trận nghịch đảo P =", P_inv)
except:
    print("P không khả nghịch.")
x = P_inv @ b
print("Nghiệm là:", x)
kiem_tra = P @ x
print("P * x =", kiem_tra)
print("Vector hằng số b =", b)
# câu 4
Q = np.array([[5, -2, 1],[0, 3, -1],[2, 0, 4]])
giatri_rieng = np.linalg.eigvals(Q)
print("Giá trị riêng =", giatri_rieng)
w, v = np.linalg.eig(Q)
print("Vector riêng tương ứng:", v)
v1 = v[:, 0] / np.linalg.norm(v[:, 0])
v2 = v[:, 1] / np.linalg.norm(v[:, 1])
v3 = v[:, 2] / np.linalg.norm(v[:, 2])
print("Vector riêng chuẩn hóa:")
print("v1 =", v1)
print("v2 =", v2)
print("v3 =", v3)

# câu 5
R = np.array([[4, -1, 2],[1, 3, -2],[0, 2, 5]])
b = np.array([12, 5, 9])
x = np.linalg.solve(R, b)
print("Nghiệm =", x)
det_R = np.linalg.det(R)
print("Định thức  =", det_R)
if det_R != 0:
    R_inv = np.linalg.inv(R)
    x_inv = R_inv @ b
    print("Ma trận nghịch đảo =", R_inv)
    print("Nghiệm (nghịch đảo) =", x_inv)
    print("Hai nghiệm giống nhau?", np.allclose(x, x_inv))
else:
    print("R không khả nghịch.")
fro_norm = np.linalg.norm(R, ord='fro')
print("Chuẩn Frobenius của R =", fro_norm)


A + B = [2 3 1 6]
2A + 3B = [ 3 11  2 14]
Tích vô hướng A · B = -5
Góc giữa A và B (độ) = 99.594
C x C^T =
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]
M x N =
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]
Định thức của M = 409.00000000000017
Hạng của ma trận N = 4
Ma trận nghịch đảo P =
 [[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]
Nghiệm của hệ là: [2.         1.71428571 0.42857143 0.85714286]
P * x = [6. 8. 3. 7.]
Vector hằng số b = [6 8 3 7]
Giá trị riêng của Q = [6.3553014+0.j         2.8223493+1.07730381j 2.8223493-1.07730381j]
Vector riêng tương ứng (cột):
 [[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]
Vector riêng chuẩn