BÀI TẬP TRÊN LỚP

In [ ]:
import numpy as np
n = 4
X = np.array(range(1, n+1))
sigma = np.array([4,3,2,1])
def sgn_def(sigma):
    ketqua = 1.0
    for i in range(len(sigma)-1):
        for j in range(i+1, len(sigma)):
            if sigma[i] != sigma[j]:
                ketqua *= (X[i] - X[j]) / (sigma[i] - sigma[j])
            else:
                return 0
    return int(ketqua)

sigma = np.array([2,1,3,4])
print(sgn_def(sigma))
sigma = np.array([1,2,3,4])
print(sgn_def(sigma))
sigma = np.array([4,3,2,1])
print(sgn_def(sigma))

from itertools import permutations
n = 3
X = []
for i in range (1, n+1):
    X.append(i)
Sn = list(permutations(X))
print(Sn)

def phatsinh_dinhthuc(n):
    X = []
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = ""
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = ""
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product + "a" + str(i) + str(sn.index(i)+1)
        dau = sgn_def(sigma)
        if dau != 1:
            product = "-" + product
        else:
            product = "+" + product
        dinhthuc = dinhthuc + product
    return dinhthuc

print(phatsinh_dinhthuc(2))
print(phatsinh_dinhthuc(3))

def tinhtoan_dinhthuc(A):
    X = []
    import math
    n = int(math.sqrt(A.size))
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = 0
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = 1
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product * A[i-1][sn.index(i)]
        dau = sgn_def(sigma)
        if dau != 1:
            product = product * (-1)
        dinhthuc = dinhthuc + product
    return dinhthuc
matran = np.array([ [3,5,-8], [4, 12, -1], [2,5,3] ])
print(tinhtoan_dinhthuc(A))
# giải hệ 2 pt
import numpy as np
A = np.array([[4, -2],[3, -5]])
A1 = np.array([[10, -2],[11, -5]])
A2 = np.array([[4, 10],[3, 11]])
from scipy import linalg
detA = linalg.det(A)
detA1 = linalg.det(A1)
detA2 = linalg.det(A2)
print (detA, detA1, detA2)
if (detA != 0):
  x1 = detA1 / detA
  x2 = detA2 / detA
print ("Hai nghiệm của phương trình là: ", x1, x2)
print(tinhtoan_dinhthuc(A))
print(tinhtoan_dinhthuc(A1))
print(tinhtoan_dinhthuc(A2))
#hệ pt tuyến tính bậc 1
import numpy as np
A = np.array([[-1, 2, -3],
              [2, -2, 1],
              [3, -4, 4]])

b = np.array([1, 3, 2])

rank_A = np.linalg.matrix_rank(A)
augmented_matrix = np.column_stack((A, b))
rank_augmented = np.linalg.matrix_rank(augmented_matrix)
if rank_A == rank_augmented:
    if rank_A == A.shape[1]:
        solution = np.linalg.solve(A, b)
        print("Hệ có nghiệm duy nhất:")
        print(f"a = {solution[0]}")
        print(f"e = {solution[1]}")
        print(f"f = {solution[2]}")
    else:
        print("Hệ có vô số nghiệm")
else:
    print("Hệ vô nghiệm")

# bài toán ứng dụng 1
import sympy as sp
TG = sp.Matrix([[1, 0, 1],[4, 3, 1], [2, 2, 1]])
1/2*TG.det()
from sympy import Matrix
M = Matrix([[0, 4, 1, 1], [4, 0, 0, 1], [3, 5, 2, 1], [2, 2, 5, 1]])
print(M.det())
print(1/6*M.det())
# ứng dụng 4
from sympy import *
x, y, z = symbols('x y z')
MP = Matrix([[x, y, z, 1],[-1, 3, 2, 1],[0, 1, 0, 1],[-2, 0, 1, 1]])
MP.det()

-1
1
1
[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]
+a11a22-a12a21
+a11a22a33-a11a23a32-a12a21a33+a13a21a32+a12a23a31-a13a22a31
0
-14.0 -28.0 14.000000000000004
Hai nghiệm của phương trình là:  2.0 -1.0000000000000002
-14
-28
14
Hệ có vô số nghiệm
-72
-12.0000000000000


-4*x + 3*y - 5*z - 3

BÀI TẬP VỀ NHÀ

In [ ]:
# bài 1
import numpy as np
A = np.array([[2, 3, 1],[1, -2, 0],[4, 1, 3]])
n = A.shape[0]
cof = np.zeros((n, n))
for i in range(n):
    for j in range(n):
        M = np.delete(np.delete(A, i, axis=0), j, axis=1)
        cof[i][j] = (-1) ** (i + j) * np.linalg.det(M)
adj = cof.T
print(A)
print(cof)
print(adj)
# bài q
from sympy import symbols, Matrix, Eq, pprint
x, y = symbols('x y')
x1, y1 = 1, 1
x2, y2 = 2, 4
x3, y3 = 5, 3
row1 = [x**2 + y**2, x, y, 1]
row2 = [x1**2 + y1**2, x1, y1, 1]
row3 = [x2**2 + y2**2, x2, y2, 1]
row4 = [x3**2 + y3**2, x3, y3, 1]
M = Matrix([row1, row2, row3, row4])
dinhthuc = M.det()
pprint(Eq(dinhthuc, 0))



[[ 2  3  1]
 [ 1 -2  0]
 [ 4  1  3]]
[[-6. -3.  9.]
 [-8.  2. 10.]
 [ 2.  1. -7.]]
[[-6. -8.  2.]
 [-3.  2.  1.]
 [ 9. 10. -7.]]
      2              2                
- 10⋅x  + 60⋅x - 10⋅y  + 40⋅y - 80 = 0
