BÀI TẬP TRÊN LỚP

In [ ]:
import numpy as np
D = np.array([[1, 2], [3, 4]])
E = np.array([[1, 2], [3, 5]])
np.copyto(E, D)
print(E)
B = np.matrix("[1 2 3; 4 5 6]")

x = np.array([['a', 'b'], ['c', 'd']])
y = 'x'
C = np.matrix([[str(x), y], [1, 2]])
print(C)
A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A)

from numpy import matlib
G = matlib.identity(5)
print(G)
H = matlib.randn(3, 2)
print(H)
K = matlib.zeros([4, 4])
print(K)

import numpy as np
c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]
M = np.matrix([[1, 2], [3, 4]])
for i in range(len(c)):
    ci = np.matrix([[1, 1], [1, 0]])
    ci[0, 0] = c[i]
    if i == 0:
        M = ci
    else:
        M = M.dot(ci)
print(M)
print(M[0, 0] / M[1, 0])

X = np.array([[1, 1], [1, 2], [1, 3], [1, 4], [1, 5]])
Y = np.array([1, 2, 4, 4, 6])
XT = X.T
A1 = np.linalg.inv(XT.dot(X))
A2 = XT.dot(Y)
A = A1.dot(A2)
print("Hệ số hồi quy tuyến tính:", A)

[[1 2]
 [3 4]]
[["[['a' 'b']\n ['c' 'd']]" 'x']
 ['1' '2']]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 0.24656019 -1.25591149]
 [ 0.48911335 -1.18095542]
 [ 0.26204843  0.019891  ]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936
Hệ số hồi quy tuyến tính: [-0.2  1.2]


BÀI TẬP VỀ NHÀ

In [ ]:
def bpcuctieu(a):
    import numpy as np
    b = []
    o1 = []
    for i in range(len(a)):
        o1.append(1.0)
        b.append(i * 1.0)
    x = np.array([o1, b])
    u = np.dot(x, x.T)
    y = np.array(a)
    from numpy import linalg
    u_1 = np.linalg.inv(u)
    v = np.dot(u_1, x)
    A = np.dot(v, y)
    return A
dulieu = [10.0, 8, 7, 5, 2]
A = bpcuctieu(dulieu)
print(f"Phương trình : y = {A[0]:.2f} + ({A[1]:.2f})*x")


Phương trình : y = 10.20 + (-1.90)*x
