BÀI TẬP TRÊN LỚP

In [ ]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
tich = np.inner(a,b)
print (tich)
print(np.dot(a,b))

import numpy as np
a = np.array([1,2,-3])
print(np.linalg.norm(a))
print(np.linalg.norm(a,1))

import math
import numpy as np
a=np.array([1,2,-3])
print(np.linalg.norm(a,1))
print(np.linalg.norm(a,2))
print(np.linalg.norm(a,3))
print(np.linalg.norm(a,1000))
from scipy import linalg
linalg.norm(a)
linalg.norm(a,100)
linalg.norm(a,1000)

import numpy as np
m = 10
v1 = np.array([5,-4,3])
v2 = np.array([4,3,-2])
v3 = np.array([-4,-3,-1])
v4 = np.array([-9,8,6])
mi = np.array([2,5,2,1])
M = np.array([v1,v2,v3,v4])
MT = M.transpose()
print(MT)
v = (1.0/m)*MT.dot(mi)
print (v)

import numpy as np
import sympy as sym
x, y = sym.symbols('x y')
xy = sym.Matrix([x,y])
A = sym.Matrix([[1, -68],[1,1]])
v = sym.Matrix([0, 1])
nghiem = sym.solve([A*xy-v])
print(sym.pretty(nghiem))

import sympy
x, y, Lambda = sympy.symbols('x y Lambda')
I = sympy.eye(2)
A = sympy.Matrix([[2,3],[3,-6]])
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0)
nghiem = sympy.solve(phuongtrinh)
print([sympy.N(phantu,4) for phantu in nghiem])
print (sympy.pretty(nghiem))

import numpy as np
A = np.array([[2,3],[3,-6]])
D = np.array([[-7,0],[0,3]])
P = np.array([[-1.0/3, 3],[1,1]])
from numpy import linalg
from numpy import linalg as LA
P1 = LA.inv(P)
print (P1)
A.dot(P)
A.dot(D)
print(P @ (D ** 1000) @ P1)
print (D **2)

32
32
3.7416573867739413
6.0
6.0
3.7416573867739413
3.3019272488946263
inf
[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]
[1.3 0.9 0. ]
⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭
[-7.000, 3.000]
[-7, 3]
[[-0.3  0.9]
 [ 0.3  0.1]]
[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]
[[49  0]
 [ 0  9]]


/usr/local/lib/python3.11/dist-packages/numpy/linalg/_linalg.py:2780: RuntimeWarning: overflow encountered in power
  absx **= ord


BÀI TẬP VỀ NHÀ

câu 1 :  
a b c d đều đúng

In [3]:
#câu 2 :
#a
import numpy as np

u = np.array([1, 2 ])
v = np.array([2, 3])

kcach = np.linalg.norm(u - v)
print("Khoảng cách:", kcach)
#b
dot_product = np.dot(u, v)
norm_u = np.linalg.norm(u)
norm_v = np.linalg.norm(v)

cos = dot_product / (norm_u * norm_v)
goc = np.arccos(np.clip(cos, -1.0, 1.0))
print("Góc :", goc)
#c
chieu = (np.dot(u, v) / np.dot(v, v)) * v
print("Phép chiếu:", chieu)


Khoảng cách: 1.4142135623730951
Góc : 0.12435499454676072
Phép chiếu: [1.23076923 1.84615385]
