BÀI TẬP TRÊN LỚP

In [22]:
import numpy as np
u = np.array([2,-1,5,0])
v = np.array([4,3,1,-1])
w = np.array([-6,2,0,3])
x = 2*u-(v+3*w)
print (x)

x = 0.5*(2*u-v-3*w)
print (x)

from numpy import linalg
A = np.matrix([[0, -1, 3],[1, 1, 1],[4, 2, 2]])
B = np.array([-1, -2, -2])
X = np.linalg.solve(A, B)
print (X)

A = np.matrix([[1,0],[0,0]])
B = np.matrix([[0,0],[0,1]])
from numpy import linalg as LA
LA.det(A)
LA.det(B)
LA.det(A+B)

import sympy as sp
x, y = sp.symbols('x y')
A = sp.Matrix([[x, y],[y, x]])
x1, y1 = sp.symbols('x1 y1')

A1 = sp.Matrix([[x1, y1],[y1, x1]])
x2, y2 = sp.symbols('x2 y2')
A2 = sp.Matrix([[x2, y2],[y2, x2]])
A1.T
print((A1+A2).T )
print(((A1+A2).T).equals(A1+A2))
c = sp.symbols('c')
print (c*A)
print(((c*A).T).equals(c*A))

import numpy as np
from numpy.linalg import solve
v1 = [1, 2, 3]
v2 = [0, 1, 2]
v3 = [-1, 0, 1]
w = [1, 1, 1]
A = np.column_stack([v1, v2, v3])
x = solve(A, w)
print("Nghiệm hệ phương trình:", x)

import sympy as sp
c1, c2, c3 = sp.symbols('c1 c2 c3')
print(sp.solve([c1-2*c3, 2*c1+c2, 3*c1+2*c2+c3], [c1, c2, c3]))

import sympy as sp
c1, c2 = sp.symbols('c1 c2')
u1, u2 = sp.symbols('u1 u2')
sp.solve([c1+c2-u1,c1-c2-u2])
u1 = 0
u2 = 0
print(sp.solve([c1+c2-u1,c1-c2-u2]))

import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,2])
P_caua = (P.T + vecdelta).T
print (P_caua)

import numpy as np
P = np.array([[0,0,3,3,1,1,2,2,1,1],[0,5,5,4,4,3,3,2,2,0]])
vecdelta = np.array([4,-2])
matran_biendoi = np.array([[1.0, 0.0],[ 0.0, 2.0]])
P_caub = (P.T @ matran_biendoi + vecdelta).T
print (P_caub)

import sympy as sp
from sympy import lambdify
x1, x2, x3 = sp.symbols('x1 x2 x3')
bieuthuc1 = x1 - x2 + x3
f1 = lambdify([x1, x2, x3], bieuthuc1, 'numpy')
a, b, c = sp.symbols('a b c')
d, e, f = sp.symbols('d e f')
print(f1(a, b, c))
print(f1(d, e, f))
f1(a+d, b+e, c+f)
f1(a,b,c) + f1(d,e,f) == f1(a+d, b+e, c+f)
(f1(a,b,c) + f1(d,e,f)).equals( f1(a+d, b+e, c+f))
q = sp.symbols('q')
(q*f1(a,b,c) + f1(d,e,f)).equals(f1(q*a+d, q*b+e, q*c+f).expand())
bieuthuc2 = 2*x2 + 3* x3
f2 = lambdify([x1, x2, x3], bieuthuc2, 'numpy')
(q*f2(a,b,c) + f2(d,e,f)).equals(f2(q*a+d, q*b+e, q*c+f).expand())

import sympy as sp
a, b = sp.symbols('a b')
x, y = sp.symbols('x y')
sp.solve([a+3*b-x, 2*a+5*b-y],[a,b])
fu1 = np.array([1,1,2])
fu2 = np.array([4,2,1])
fu = a*fu1 + b*fu2
print (fu)
fu = a.subs(a, -5*x + 3*y)*fu1 + b.subs(b, 2*x - y)*fu2
print (fu)

x1, x2, x3 = sp.symbols('x1 x2 x3')
sp.solve([x1+x2-x3, 2*x1+3*x2-x3, 3*x1+5*x2-x3],[x1, x2, x3])

import numpy as np
import math
from scipy import linalg as LA
B = np.matrix([[1.0/math.sqrt(2), 1.0/math.sqrt(2)],[-1.0/math.sqrt(2),1.0/math.sqrt(2)]])
LA.orth(B)
1.0/math.sqrt(2)

[ 18 -11   9  -8]
[ 9.  -5.5  4.5 -4. ]
[ 1. -2. -1.]
Matrix([[x1 + x2, y1 + y2], [y1 + y2, x1 + x2]])
True
Matrix([[c*x, c*y], [c*y, c*x]])
True
Nghiệm hệ phương trình: [ 5.00000000e-01 -1.66533454e-16 -5.00000000e-01]
{c1: 0, c2: 0, c3: 0}
{c1: 0, c2: 0}
[[4 4 7 7 5 5 6 6 5 5]
 [2 7 7 6 6 5 5 4 4 2]]
[[ 4.  4.  7.  7.  5.  5.  6.  6.  5.  5.]
 [-2.  8.  8.  6.  6.  4.  4.  2.  2. -2.]]
a - b + c
d - e + f
[a + 4*b a + 2*b 2*a + b]
[3*x - y -x + y -8*x + 5*y]


array([[-0.70710678,  0.70710678],
       [ 0.70710678,  0.70710678]])

BÀI TẬP VỀ NHÀ

In [30]:
import numpy as np

def g(v):
    x, y, z = v
    return np.array([x + y, z + 2, 0])
u = np.array([1, 2, 3])
v = np.array([4, -1, 0])
c = 3
left_add = g(u + v)
right_add = g(u) + g(v)
left_scalar = g(c * u)
right_scalar = c * g(u)
print("Kiểm tra tính cộng:")
print("g(u + v)       =", left_add)
print("g(u) + g(v)    =", right_add)
if  np.allclose(left_add, right_add) == True :
 print("Kiểm tra tính nhân vô hướng:")
 print("g(c * u)       =", left_scalar)
 print("c * g(u)       =", right_scalar)
 print("Kết luận: không phải ánh xạ tuyến tính")
else :
  print("Kết luận: không phải ánh xạ tuyến tính")

import numpy as np
A = np.array([[0, 1],[1, -1]])
F = np.array([[0, 1, 1, 0], [0, 0, 1, 1]])
F_doi = A @ F
print("Tọa độ điểm ban đầu (F):")
print(F)
print("Tọa độ sau biến đổi f(F) = A --> F:")
print(F_doi)

import sympy as sp
v1, v2 = sp.symbols('v1 v2')
u1, u2 = sp.symbols('u1 u2')
c = sp.symbols('c')
def T(v1, v2):
    return sp.Matrix([v1 - v2, v1 + 2*v2])
T_add = T(u1 + v1, u2 + v2)
T_u = T(u1, u2)
T_v = T(v1, v2)
T_u_plus_T_v = T_u + T_v
if T_add.equals(T_u_plus_T_v)== True :
  T_cv = T(c*v1, c*v2)
  c_Tv = c * T(v1, v2)
  if  T_cv.equals(c_Tv)==True :
    print("Kết luận: là ánh xạ tuyến tính")
  else :
    print("Kết luận: không phải ánh xạ tuyến tính")





Kiểm tra tính cộng:
g(u + v)       = [6 5 0]
g(u) + g(v)    = [6 7 0]
Kết luận: không phải ánh xạ tuyến tính
Tọa độ điểm ban đầu (F):
[[0 1 1 0]
 [0 0 1 1]]
Tọa độ sau biến đổi f(F) = A --> F:
[[ 0  0  1  1]
 [ 0  1  0 -1]]
Kết luận: là ánh xạ tuyến tính
