In [12]:
# câu 1:
import numpy as np
A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])
tong = A + B
tich_so = 3*A - 2*B
print("A + B =", tong)
print("3A - 2B =", tich_so)
tich_vo_huong = np.dot(A, B)
print("tich vo huong = ", tich_vo_huong)
C = np.array([[1, 2, -1],[0, 3, 4],[2, -1, 0]])
ketqua = np.dot(C.T,C )
print('tich ma tran chuyen vi la',ketqua)
# câu 2
import numpy as np
M = np.array([[1, 2, 3, 0],[4, 5, 6, 1],[7, 8, 9, 2],[0, 1, 1, 0]])
N = np.array([[0, 1, 2, 3],[4, 5, 6, 7],[8, 9, 10, 11],[12, 13, 14, 15]])
MN = M.dot(N)
print("M x N = ", MN)
from scipy import linalg
import numpy as np
M = np.array([[1, 2, 3, 0],[4, 5, 6, 1],[7, 8, 9, 2],[0, 1, 1, 0]])
dinh_thuc = linalg.det(M)
print("Định thức", dinh_thuc)
hang = np.linalg.matrix_rank(M)
print("Hạng ma trận ", hang)
# câu 3
import numpy as np
P = np.array([[2, 1, 0, 1],[0, 3, 1, -1],[1, 0, 4, 2],[0, 1, 0, 3]])
b = np.array([4, 7, 9, 5])
from scipy import linalg
nghich_dao_P = linalg.inv(P)
print("Ma trận nghịch đảo", nghich_dao_P)
nghiem = np.dot(nghich_dao_P, b)
print("Nghiệm của hệ là:", nghiem)
kiem_tra = P.dot(nghiem)
print("P * x =", kiem_tra)
print("Vector hằng số b =", b)
# câu 4
import numpy as np
Q = np.array([[4, -1, 0],[1, 3, -2],[0, 1, 2]])
giatri_rieng = np.linalg.eigvals(Q)
print("Giá trị riêng ", giatri_rieng)
w, v = np.linalg.eig(Q)
print("Vector riêng tương ứng  ", v)
v1 = v[:,0] / np.linalg.norm(v[:,0])
v2 = v[:,1] / np.linalg.norm(v[:,1])
v3 = v[:,2] / np.linalg.norm(v[:,2])
print("Vector riêng chuẩn hóa:")
print("v1 =", v1)
print("v2 =", v2)
print("v3 =", v3)
# câu 5
import numpy as np
R = np.array([[1, -2, 3],[2, 0, 1],[-1, 1, 4]])
b = np.array([10, 8, 7])
x = np.linalg.solve(R, b)
print("Nghiệm x =", x)
det_R = np.linalg.det(R)
print("Định thức của R =", det_R)
if det_R != 0:
    R_inv = np.linalg.inv(R)
    print("Ma trận nghịch đảo ", R_inv)
    x_inv = R_inv @ b
    print("Nghiệm x (dùng nghịch đảo):", x_inv)
    print("Hai nghiệm giống nhau?", np.allclose(x, x_inv))
else:
    print("Ma trận R không khả nghịch, không thể tính nghịch đảo.")
fro_norm = np.linalg.norm(R, ord='fro')
print("Chuẩn Frobenius của R:", fro_norm)





A + B = [3 3 1 5]
3A - 2B = [  4 -11  13 -10]
tich vo huong =  -8
tich ma tran chuyen vi la [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]
M x N =  [[ 32  38  44  50]
 [ 80  96 112 128]
 [128 154 180 206]
 [ 12  14  16  18]]
Định thức 0.0
Hạng ma trận  3
Ma trận nghịch đảo [[ 0.48837209 -0.09302326  0.02325581 -0.20930233]
 [ 0.03488372  0.27906977 -0.06976744  0.12790698]
 [-0.11627907  0.06976744  0.23255814 -0.09302326]
 [-0.01162791 -0.09302326  0.02325581  0.29069767]]
Nghiệm của hệ là: [0.46511628 2.10465116 1.65116279 0.96511628]
P * x = [4. 7. 9. 5.]
Vector hằng số b = [4 7 9 5]
Giá trị riêng  [3.45339765+0.j         2.77330117+1.46771151j 2.77330117-1.46771151j]
Vector riêng tương ứng   [[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743-0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]
Vector riêng chuẩn hóa:
v1 = [0.83327121+0.j 0.455468  +0.j 0.31338154+0.j]
v2 